from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('quemSomos', views.Somos),
    path('base_telainicial', views.Base_telainicial),
    path('solucoes', views.Solucoes),
    path('cadastro', views.Cad, name='cadastro'),
    path('comorbidades_list', views.Comorbidades_list, name='comorbidades_list'),
    path('comorbidades_add', views.Comorbidades_add, name='comorbidades_form'),
    path('comorbidades_edit/<int:id>', views.Comorbidades_edit, name="comorbidades_form"),
    path('comorbidades_delete/<int:id>', views.Comorbidades_delete, name="comorbidades_delete"),
    path('telainicial', views.Inicial, name='telainicial'),
    path('agenda', views.Agenda),
    path('uso_consumo_list', views.Uso_Consumo_list, name='uso_consumo_list'),
    path('uso_consumo_add', views.Uso_Consumo_add, name='uso_consumo_form'),
    path('uso_consumo_edit/<int:id>', views.Uso_Consumo_edit, name="uso_consumo_form"),
    path('uso_consumo_delete/<int:id>', views.Uso_Consumo_delete, name="uso_consumo_delete"),
    path('estoque_individual_list', views.Estoque_Individual_list, name='estoque_individual_list'),
    path('estoque_individual_add/<str:nome>', views.Estoque_Individual_add, name='estoque_individual_form'),
    path('ocorrencias_list', views.Ocorrencias_list, name='ocorrencias_list'),
    path('ocorrencias_add', views.Ocorrencias_add, name='ocorrencias_form'),
    path('ocorrencias_edit/<int:id>', views.Ocorrencias_edit, name='ocorrencias_form'),
    path('ocorrencias_delete/<int:id>', views.Ocorrencias_delete, name='ocorrencias_delete'),
    path('residentes_list', views.Residentes_list, name='residente_list'),
    path('residentes_add', views.Residentes_add, name='residentes_form'),
    path('residentes_edit/<int:id>', views.Residentes_edit, name='residentes_form'),
    path('residentes_delete/<int:id>', views.Residentes_delete, name='residentes_delete'),
    path('calendario/', views.CalendarView.as_view(), name='calendario'),
    path('cuidadores_list', views.Cuidadores_list, name='cuidadores_list'),
    path('cuidadores_add', views.Cuidadores_add, name='cuidadores_form'),
    path('cuidadores_edit/<int:id>', views.Cuidadores_edit, name='cuidadores_form'),
    path('cuidadores_delete/<int:id>', views.Cuidadores_delete, name='cuidadores_delete'),
    path('responsavel_list', views.Responsavel_list, name='responsavel_list'),
    path('responsavel_add', views.Responsavel_add, name='responsavel_form'),
    path('responsavel_edit/<int:id>', views.Responsavel_edit, name='responsavel_form'),
    path('responsavel_delete/<int:id>', views.Responsavel_delete, name='responsavel_delete'),
    path('prescricao_list', views.Prescricao_list, name='prescricao_list'),
    path('prescricao_add', views.Prescricao_add, name='prescricao_form'),
    path('prescricao_edit/<int:id>', views.Prescricao_edit, name='prescricao_form'),
    path('prescricao_delete/<int:id>', views.Prescricao_delete, name='prescricao_delete'),
    #path('email', views.Envia_email, name='envia_email'),
    # path('estoque_edit/<int:id>', views.Estoque_edit, name="estoque_edit"),
    # path('estoque_delete/<int:id>', views.Estoque_delete, name="estoque_delete"),
]
