# Generated by Django 4.1 on 2022-09-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_nome', models.CharField(default='', max_length=100, verbose_name='Cidade')),
                ('cidade_uf', models.CharField(default='', max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['cidade_nome'],
            },
        ),
        migrations.CreateModel(
            name='Comorbidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidade_nome', models.CharField(default='', max_length=50, verbose_name='Comorbidade')),
            ],
            options={
                'verbose_name': 'Comorbidade',
                'verbose_name_plural': 'Comorbidades',
                'ordering': ['comorbidade_nome'],
            },
        ),
        migrations.CreateModel(
            name='Estoque_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoqueCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('estoque_pessoa_nome', models.CharField(max_length=50)),
                ('estoque_movimento', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida')], default='', max_length=1)),
                ('estoque_quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('estoque_saldo', models.IntegerField(default=0, verbose_name='Saldo em Estoque')),
            ],
            options={
                'verbose_name': 'Estoque Individual',
                'verbose_name_plural': 'Estoque Individuais',
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_nome', models.CharField(default='', max_length=50, verbose_name='Nome')),
                ('pessoa_endereco', models.CharField(default='', max_length=100, verbose_name='Endereco')),
                ('pessoa_numero', models.CharField(default='', max_length=10, verbose_name='Numero')),
                ('pessoa_compl', models.CharField(default='', max_length=30, verbose_name='Complemento')),
                ('pessoa_CPF', models.CharField(default=0, max_length=11, verbose_name='CPF')),
                ('pessoa_classe', models.CharField(choices=[('1', 'Cuidador'), ('2', 'Residente'), ('3', 'Responsavel')], default='', max_length=1)),
                ('pessoa_telefone', models.CharField(default=0, max_length=20, verbose_name='Telefone')),
                ('pessoa_email', models.EmailField(default='', max_length=254, verbose_name='E-mail')),
                ('pessoa_plano', models.CharField(choices=[('1', 'PARTICULAR'), ('2', 'SUS'), ('3', 'CONVENIO')], default='', max_length=1)),
                ('pessoa_cidade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.cidades', verbose_name='Cidade')),
                ('pessoa_comorbidade', models.ManyToManyField(to='app1.comorbidades', verbose_name='Comorbidades')),
                ('pessoa_estoque_individual', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.estoque_individual', verbose_name='Estoque_Individual')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['pessoa_nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoas_Comorbidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_comorbidade_nome', models.CharField(default=0, max_length=10, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Uso_Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_nome', models.CharField(default='', max_length=50, verbose_name='Uso e consumo')),
                ('consumo_fabricante', models.CharField(default='', max_length=50, verbose_name='Fabricante')),
                ('consumo_apresentacao', models.CharField(choices=[('1', 'Comprimido'), ('2', 'Dragea'), ('3', 'Gota'), ('4', 'Injetavel'), ('5', 'Ampola'), ('6', 'Bisnaga'), ('7', 'Unidade')], default='', max_length=1, verbose_name='Apresentacao')),
                ('consumo_via', models.CharField(choices=[('1', 'Oral'), ('2', 'Intra-Venoso'), ('3', 'Nasal'), ('4', 'Ocular')], default='', max_length=1)),
            ],
            options={
                'verbose_name': 'Uso e consumo',
                'ordering': ['consumo_nome'],
            },
        ),
        migrations.CreateModel(
            name='SinalVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinalVitalCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('sinalVital_pas', models.CharField(default='', max_length=5, verbose_name='PAS')),
                ('sinalVital_pad', models.CharField(default='', max_length=5, verbose_name='PAD')),
                ('sinalVital_fc', models.CharField(default='', max_length=5, verbose_name='FC')),
                ('sinalVital_fr', models.CharField(default='', max_length=5, verbose_name='FR')),
                ('sinalVital_temp', models.CharField(default='', max_length=5, verbose_name='TEMP')),
                ('sinalVital_peso', models.IntegerField(default=0, verbose_name='Peso')),
                ('sinalVital_altura', models.IntegerField(default=0, verbose_name='Altura')),
                ('sinalVital_IMC', models.IntegerField(default=0, verbose_name='IMC')),
                ('sinalVital_pessoa_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Sinal Vital',
                'verbose_name_plural': 'Sinais Vitais',
                'ordering': ['sinalVital_pessoa_nome'],
            },
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescricao_frequencia', models.CharField(choices=[('1', 'Horario'), ('2', 'Diario'), ('3', 'Semanal'), ('4', 'Mensal')], default='', max_length=1)),
                ('prescricao_aprazamento', models.TimeField(verbose_name='Aprazamento')),
                ('prescricao_dose', models.CharField(choices=[('1', '1/4'), ('2', '1/2'), ('3', '3/4'), ('4', '1'), ('5', '1 + 1/4'), ('6', '1 + 1/2'), ('7', '1 + 3/4')], default='', max_length=1)),
                ('prescricao_inicio', models.DateField(default='', max_length=10, verbose_name='Data Inicio')),
                ('prescricao_fim', models.DateField(default='', max_length=10, verbose_name='Data Fim')),
                ('prescricao_observacao', models.CharField(default='', max_length=200, verbose_name='Observacao')),
                ('prescricao_consumo_nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.uso_consumo', verbose_name='Produto')),
                ('prescricao_pessoa_nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Prescricao',
                'verbose_name_plural': 'Prescricoes',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia_nome', models.CharField(choices=[('1', 'Disturbio'), ('2', 'Queda'), ('3', 'Fisioterapia'), ('4', 'Consulta Medica'), ('5', 'Refeicao'), ('6', 'Quimioterapia'), ('7', 'Outros')], default='', max_length=1, verbose_name='Ocorrencia')),
                ('ocorrencia_pessoa_cuidador', models.CharField(default=0, max_length=50, verbose_name='Cuidador')),
                ('ocorrencia_pessoa_nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventoCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('evento_observacao', models.CharField(default='', max_length=100, verbose_name='Observacao')),
                ('evento_pessoa_nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['evento_pessoa_nome'],
            },
        ),
        migrations.AddField(
            model_name='estoque_individual',
            name='estoque_usos_consumo',
            field=models.ManyToManyField(to='app1.uso_consumo', verbose_name='Produto'),
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentoCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('documento_nome', models.CharField(default='', max_length=50, verbose_name='Documentos')),
                ('documento_arquivo', models.FileField(default='', upload_to='', verbose_name='Upload')),
                ('documento_pessoa_nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Documento',
                'ordering': ['documento_pessoa_nome'],
            },
        ),
    ]
