# Generated by Django 4.1 on 2022-09-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_nome', models.CharField(default='', max_length=100, verbose_name='Cidade')),
                ('cidade_uf', models.CharField(default='', max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['cidade_nome'],
            },
        ),
        migrations.CreateModel(
            name='Comorbidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidade_nome', models.CharField(default='', max_length=50, verbose_name='Comorbidade')),
            ],
            options={
                'verbose_name': 'Comorbidade',
                'verbose_name_plural': 'Comorbidades',
                'ordering': ['comorbidade_nome'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('pessoa_endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereco')),
                ('pessoa_numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero')),
                ('pessoa_compl', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento')),
                ('pessoa_CPF', models.CharField(default=0, max_length=11, unique=True, verbose_name='CPF')),
                ('pessoa_classe', models.IntegerField(choices=[(1, 'Cuidador'), (2, 'Residente'), (3, 'Responsavel')])),
                ('pessoa_telefone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone')),
                ('pessoa_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('pessoa_plano', models.IntegerField(blank=True, choices=[(1, 'PARTICULAR'), (2, 'SUS'), (3, 'CONVENIO')], null=True)),
                ('pessoa_cidade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.cidades', verbose_name='Cidade')),
                ('pessoa_comorbidade', models.ManyToManyField(to='app1.comorbidades', verbose_name='Comorbidades')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['pessoa_nome'],
            },
        ),
        migrations.CreateModel(
            name='Uso_Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_nome', models.CharField(default='', max_length=50, verbose_name='Uso e consumo')),
                ('consumo_fabricante', models.CharField(default='', max_length=50, verbose_name='Fabricante')),
                ('consumo_apresentacao', models.IntegerField(choices=[(1, 'Comprimido'), (2, 'Dragea'), (3, 'Gota'), (4, 'Injetavel'), (5, 'Ampola'), (6, 'Bisnaga'), (7, 'Unidade'), (8, 'Adesivo'), (9, 'Aerosol'), (10, 'Bolsa'), (11, 'Capsula'), (12, 'Colirio'), (13, 'Creme'), (14, 'Envelope'), (15, 'Inalatorio'), (16, 'Injetavel UI'), (17, 'Pilula'), (18, 'Pomada'), (19, 'Sache'), (20, 'Seringa'), (21, 'Shampoo'), (22, 'Solucao Gotas'), (23, 'Solucao ML'), (24, 'Solucao UI'), (25, 'Suspencao'), (26, 'Xarope'), (27, 'Tablete')], default=None, verbose_name='Apresentacao')),
                ('consumo_via', models.IntegerField(choices=[(1, 'Oral'), (2, 'Intra-Venoso'), (3, 'Nasal'), (4, 'Ocular'), (5, 'Intramuscular'), (6, 'Topico'), (7, 'Nebulizacao'), (8, 'Otologica'), (9, 'Retal'), (10, 'Sonda-Nasoenteral'), (11, 'Gastrostomia'), (12, 'Sub-cutanea'), (13, 'Sub-lingual'), (14, 'Vaginal')], default=None)),
            ],
            options={
                'verbose_name': 'Uso e consumo',
                'ordering': ['consumo_nome'],
            },
        ),
        migrations.CreateModel(
            name='SinalVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinalVitalCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('sinalVital_pas', models.CharField(default='', max_length=5, verbose_name='PAS')),
                ('sinalVital_pad', models.CharField(default='', max_length=5, verbose_name='PAD')),
                ('sinalVital_fc', models.CharField(default='', max_length=5, verbose_name='FC')),
                ('sinalVital_fr', models.CharField(default='', max_length=5, verbose_name='FR')),
                ('sinalVital_temp', models.CharField(default='', max_length=5, verbose_name='TEMP')),
                ('sinalVital_peso', models.IntegerField(default=0, verbose_name='Peso')),
                ('sinalVital_altura', models.IntegerField(default=0, verbose_name='Altura')),
                ('sinalVital_IMC', models.IntegerField(default=0, verbose_name='IMC')),
                ('sinalVital_pessoa_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Sinal Vital',
                'verbose_name_plural': 'Sinais Vitais',
                'ordering': ['sinalVital_pessoa_nome'],
            },
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescricao_frequencia', models.IntegerField(choices=[(1, 'Horario'), (2, 'Diario'), (3, 'Semanal'), (4, 'Mensal'), (5, 'Dias Alternados'), (6, 'Criterio Medico')], default='')),
                ('prescricao_aprazamento', models.TimeField(verbose_name='Aprazamento')),
                ('prescricao_dose', models.IntegerField(choices=[(1, '1/4'), (2, '1/2'), (3, '3/4'), (4, '1'), (5, '1 + 1/4'), (6, '1 + 1/2'), (7, '1 + 3/4')], default='')),
                ('prescricao_inicio', models.DateField(default='', max_length=10, verbose_name='Data Inicio')),
                ('prescricao_fim', models.DateField(default='', max_length=10, verbose_name='Data Fim')),
                ('prescricao_observacao', models.CharField(default='', max_length=200, verbose_name='Observacao')),
                ('prescricao_consumo_nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.uso_consumo', verbose_name='Produto')),
                ('prescricao_pessoa_nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Prescricao',
                'verbose_name_plural': 'Prescricoes',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia_nome', models.IntegerField(choices=[(1, 'Agressividade'), (2, 'Alteracoes Glicemia'), (3, 'Cefaleia'), (4, 'Convulcao'), (5, 'Cuidado Paliativo'), (6, 'Deficit Motor'), (7, 'Desidratacao'), (8, 'Desnutricao'), (9, 'Diarreia'), (10, 'Doencas Respiratorias'), (11, 'Dor Abdominal'), (12, 'Dor Epigastrica'), (13, 'dor Torassica'), (14, 'Entorce'), (15, 'Escabiose'), (16, 'Febre'), (17, 'FR Alterada'), (18, 'Ematoma'), (19, 'Infeccao TRato Urinario'), (20, 'Internacao'), (21, 'Lesao de Pele'), (22, 'Liberacao de Cateteres e Sondas'), (23, 'Modificacao de Prescricao'), (24, 'Neutropenia Febril'), (25, 'Obito'), (26, 'PA Alterada'), (27, 'Queda'), (28, 'Retirada de Dispositivo')], default='', verbose_name='Ocorrencia')),
                ('ocorrencia_pessoa_cuidador', models.CharField(default=0, max_length=50, verbose_name='Cuidador')),
                ('ocorrencia_observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ocorrencia_pessoa_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventoCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('evento_observacao', models.CharField(default='', max_length=100, verbose_name='Observacao')),
                ('evento_pessoa_nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['evento_pessoa_nome'],
            },
        ),
        migrations.CreateModel(
            name='Estoque_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoqueCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('estoque_movimento', models.CharField(choices=[(1, 'Entrada'), (2, 'Saida')], default='', max_length=1)),
                ('estoque_quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('estoque_saldo', models.IntegerField(default=0, verbose_name='Saldo em Estoque')),
                ('estoque_pessoa_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
                ('estoque_usos_consumo', models.ManyToManyField(to='app1.uso_consumo', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque Individual',
                'verbose_name_plural': 'Estoque Individuais',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentoCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('documento_nome', models.CharField(default='', max_length=50, verbose_name='Documentos')),
                ('documento_arquivo', models.FileField(default='', upload_to='', verbose_name='Upload')),
                ('documento_pessoa_nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Documento',
                'ordering': ['documento_pessoa_nome'],
            },
        ),
    ]
