# Generated by Django 4.1 on 2022-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencias',
            name='ocorrencia_nome',
            field=models.IntegerField(choices=[(1, 'Agressividade'), (2, 'Alteracoes Glicemia'), (3, 'Cefaleia'), (4, 'Convulcao'), (5, 'Cuidado Paliativo'), (6, 'Deficit Motor'), (7, 'Desidratacao'), (8, 'Desnutricao'), (9, 'Diarreia'), (10, 'Doencas Respiratorias'), (11, 'Dor Abdominal'), (12, 'Dor Epigastrica'), (13, 'dor Torassica'), (14, 'Entorce'), (15, 'Escabiose'), (16, 'Febre'), (17, 'FR Alterada'), (18, 'Ematoma'), (19, 'Infeccao TRato Urinario'), (20, 'Internacao'), (21, 'Lesao de Pele'), (22, 'Liberacao de Cateteres e Sondas'), (23, 'Modificacao de Prescricao'), (24, 'Neutropenia Febril'), (25, 'Obito'), (26, 'PA Alterada'), (27, 'Queda'), (28, 'Retirada de Dispositivo')], default='', verbose_name='Ocorrencia'),
        ),
    ]
