# Generated by Django 4.1 on 2022-09-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencias',
            name='ocorrencia_pessoa_nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente'),
        ),
    ]
