# Generated by Django 4.1 on 2022-10-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinalvital',
            name='sinalVital_altura',
            field=models.FloatField(default=0, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='sinalvital',
            name='sinalVital_peso',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
    ]
