# Generated by Django 4.1 on 2022-09-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescricao',
            options={'verbose_name': 'Prescricao', 'verbose_name_plural': 'Prescricoes'},
        ),
    ]
