# Generated by Django 4.1 on 2022-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='pessoa_CEP',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_CPF',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_telefone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Telefone'),
        ),
    ]
