# Generated by Django 4.1 on 2022-09-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_ocorrencias_ocorrencia_pessoa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_classe',
            field=models.CharField(choices=[('1', 'Cuidador'), ('2', 'Residente'), ('3', 'Responsavel')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_comorbidade',
            field=models.ManyToManyField(blank=True, to='app1.comorbidades', verbose_name='Comorbidades'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_compl',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_plano',
            field=models.CharField(blank=True, choices=[('1', 'PARTICULAR'), ('2', 'SUS'), ('3', 'CONVENIO')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
