# Generated by Django 4.1 on 2022-10-20 17:14

from django.db import migrations


Comorbidades_default = [
    ("Asma em Uso de Corticoide Inalatorio ou Sistomico"),
    ("Doenca Pulmonar Obstrutiva Cronica (DPOC)"),
    ("Bronquiectasia"),
    ("Fibrose Ci­stica"),
    ("Doencas Intersticiais do Pulmao"),
    ("Displasia Broncopulmonar"),
    ("Hipertensao Arterial Pulmonar"),
    ("Doenca Cardi­aca Congenita"),
    ("Hipertensao Arterial Sistemica com Comorbidade"),
    ("Doenca Cardi­aca Isquemica"),
    ("Insuficiencia Cardiaca"),
    ("Doenca Renal nos Estagios 3,4 e 5"),
    ("Sindrome Nefratica"),
    ("Paciente em Dialise"),
    ("Atresia Biliar"),
    ("Hepatites Cronicas"),
    ("Cirrose"),
    ("Funcao Respiratoria Comprometida"),
    ("Acidente Vascular Cerebral"),
    ("Individuos com Paralisia Cerebral"),
    ("Esclerose Multipla"),
    ("Doencas Hereditarias"),
    ("Doencas Degenerativas"),
    ("Deficiencia Neurologica Grave"),
    ("Diabetes tipo I e tipo II"),
    ("Imunodeficiencia"),
    ("Obesidade Grau III"),
    ("Sindrome de Down"),
    ("Si­ndrome de Klinefelter"),
    ("Sindrome de Wakany")
]

def CREATE_Comorbidades(apps, schema_editor):
    comorbidades = apps.get_model('app1', 'Comorbidades')

    for comorbidade_nome in Comorbidades_default:
        comorbidades.objects.create(
            comorbidade_nome = comorbidade_nome
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20221020_1712'),
    ]

    operations = [
        migrations.RunPython(CREATE_Comorbidades)
    ]
