# Generated by Django 4.1 on 2022-09-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_uso_consumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_individual',
            name='estoque_pessoa_nome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.pessoas', verbose_name='Residente'),
        ),
    ]
