# Generated by Django 4.1 on 2022-10-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_sinalvital_sinalvital_imc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_nome', models.CharField(default='', max_length=50, verbose_name='Uso e consumo')),
                ('medicamento_fabricante', models.CharField(default='', max_length=50, verbose_name='Fabricante')),
                ('medicamento_apresentacao', models.IntegerField(choices=[(1, 'Comprimido'), (2, 'Dragea'), (3, 'Gota'), (4, 'Injetavel'), (5, 'Ampola'), (6, 'Bisnaga'), (7, 'Unidade'), (8, 'Adesivo'), (9, 'Aerosol'), (10, 'Bolsa'), (11, 'Capsula'), (12, 'Colirio'), (13, 'Creme'), (14, 'Envelope'), (15, 'Inalatorio'), (16, 'Injetavel UI'), (17, 'Pilula'), (18, 'Pomada'), (19, 'Sache'), (20, 'Seringa'), (21, 'Shampoo'), (22, 'Solucao Gotas'), (23, 'Solucao ML'), (24, 'Solucao UI'), (25, 'Suspencao'), (26, 'Xarope'), (27, 'Tablete')], default=None, verbose_name='Apresentacao')),
                ('medicamento_via', models.IntegerField(choices=[(1, 'Oral'), (2, 'Intra-Venoso'), (3, 'Nasal'), (4, 'Ocular'), (5, 'Intramuscular'), (6, 'Topico'), (7, 'Nebulizacao'), (8, 'Otologica'), (9, 'Retal'), (10, 'Sonda-Nasoenteral'), (11, 'Gastrostomia'), (12, 'Sub-cutanea'), (13, 'Sub-lingual'), (14, 'Vaginal')], default=None)),
            ],
            options={
                'verbose_name': 'Medicamentos',
                'ordering': ['medicamento_nome'],
            },
        ),
        migrations.AlterField(
            model_name='estoque_individual',
            name='estoque_usos_consumo',
            field=models.ManyToManyField(to='app1.medicamentos', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_consumo_nome',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.medicamentos', verbose_name='Uso_consumo'),
        ),
        migrations.DeleteModel(
            name='Uso_Consumo',
        ),
    ]
