# Generated by Django 4.1 on 2022-10-20 17:15

from django.db import migrations


Medicamentos_default = [
    ("NEOSORO","Neo Quimica",3,3),
    ("GLIFAGE XR","Merck S.A",1,1),
    ("MAXALGINA","Natulab",3,1),
    ("LOSARTANA N.Q","Sanofi Medley",1,1),
    ("CIMEGRIPE","Cimed",11,1),
    ("CICLO 21","Uniao Quimica",1,1),
    ("PURAN T4","SANOFI-AVENTIS",1,1),
    ("LOSARTANA TTB","Sanofi Medley",1,1),
    ("CIMELIDE","Cimed",1,1),
    ("TORSILAX","Neo Quimica",1,1),
    ("DORFLEX","Sanofi",1,1),
    ("SILDENAFILA N.Q","Legrand",1,1),
    ("METFORMINA P.D","Merck S.A",3,3),
    ("LOSARTANA EMS","Neo Quimica",1,1),
    ("DIPIMED","Merck S.A",3,1),
    ("SALONPAS EMPLASTRO","Natulab",1,1),
    ("LORATAMED","Sanofi Medley",11,1),
    ("HIDROCLOROTIAZIDA","Cimed",1,1),
    ("LOSARTANA MD7","Uniao Quimica",1,1),
    ("NOVALGINA","SANOFI-AVENTIS",1,1),
    ("ARADOIS","Sanofi Medley",1,1),
    ("SORIMAX","Cimed",1,1),
    ("BUSCOPAN CPTO","Neo Quimica",1,1),
    ("LEVOTIROXINA MCK","Sanofi",1,1),
    ("HISTAMIN","Legrand",3,3),
    ("SILDENAFILA EUF","Merck S.A",1,1),
    ("EXPEC","Neo Quimica",3,1),
    ("STREPSILS","Merck S.A",1,1),
    ("VICK-VAPORUB","Natulab",11,1),
    ("MICROVLAR","Sanofi Medley",1,1),
    ("INFRALAX","Cimed",1,1),
    ("LOSARTANA P.D","Uniao Quimica",1,1),
    ("ATENOLOL SDZ","SANOFI-AVENTIS",1,1),
    ("VITER C","Sanofi Medley",1,1),
    ("DIPIRONA N.Q","Cimed",1,1),
    ("DECONGEX PLUS","Neo Quimica",1,1),
    ("DIPIRONA EMS","Sanofi",3,3),
    ("HIDROCLOROTIAZIDA MDQ","Legrand",1,1),
    ("IBUPRIL","Merck S.A",3,1),
    ("ENALAPRIL TTB","Neo Quimica",1,1),
    ("RIVOTRIL","Merck S.A",11,1),
    ("SORO FISIOLOGICO ADV","Natulab",1,1),
    ("NEOSALDINA","Sanofi Medley",1,1),
    ("NIMESULIDA CM5","Cimed",1,1),
    ("TYLEMAX","Uniao Quimica",1,1),
    ("GLIBENCLAMIDA N.Q","SANOFI-AVENTIS",1,1),
    ("ATENOLOL MD7","Sanofi Medley",1,1),
    ("SINVASTATINA SDZ","Cimed",1,1),
    ("HIDROCLOROTIAZIDA TTB","Neo Quimica",3,3),
    ("FLUCONAZOL CM5","Sanofi",1,1),
    ("CEFALEXINA TTB","Legrand",3,1),
    ("DORALGINA","Merck S.A",1,1),
    ("DIAD","Neo Quimica",11,1),
    ("BIO-C","Merck S.A",1,1),
    ("NARIDRIN","Natulab",1,1),
    ("SAL DE FRUTA ENO","Sanofi Medley",1,1),
    ("BABYMED","Cimed",1,1),
    ("AEROLIN","Uniao Quimica",1,1),
    ("CORUS","SANOFI-AVENTIS",1,1),
    ("DRAMIN B6","Sanofi Medley",1,1),
    ("HIDROCLOROTIAZIDA N.Q","Cimed",3,3),
    ("BEPANTRIZ","Neo Quimica",1,1),
    ("ALBEL","Sanofi",3,1),
    ("COLIRIO","Legrand",1,1),
    ("ENALAPRIL CM5","Merck S.A",11,1),
    ("CIFLOGEX","Neo Quimica",1,1),
    ("NEODIA","Merck S.A",1,1),
    ("SIMETICONA MD7","Natulab",1,1),
    ("SCAFLOGIN","Sanofi Medley",1,1),
    ("SOMALGIN CARDIO","Cimed",1,1),
    ("LOSARTANA POT EUF","Uniao Quimica",1,1),
    ("CETOPROFENO MD7","SANOFI-AVENTIS",1,1),
    ("NARIX","Sanofi Medley",3,3),
    ("NISTA+ZINCO N.Q","Cimed",1,1),
    ("OMEPRAZOL TTB","Neo Quimica",3,1),
    ("LACRIFILM","Sanofi",1,1),
    ("NAPROXENO N.Q","Legrand",11,1),
    ("PREDSIM","Merck S.A",1,1),
    ("LOSARTANA GM2","Neo Quimica",1,1),
    ("BUSONID","Merck S.A",1,1),
    ("NEOLEFRIN","Natulab",1,1),
    ("SODIO CLORET. ARB","Sanofi Medley",1,1),
    ("HIDROCLOROTIAZIDA EMS","Cimed",1,1),
    ("BUSCOPAN","Uniao Quimica",1,1),
    ("ALBENDAZOL MD7","SANOFI-AVENTIS",3,3),
    ("GARDENAL","Sanofi Medley",1,1),
    ("SELOZOK","Cimed",3,1),
    ("PANTOPRAZOL ACH","Neo Quimica",1,1),
    ("LUFTAL","Sanofi",11,1),
    ("TADALAFILA EUF","Legrand",1,1),
    ("REPOFLOR","Merck S.A",1,1),
    ("RINOSORO","Neo Quimica",1,1),
    ("SINVASTATINA CM5","Merck S.A",1,1),
    ("ADVIL","Natulab",1,1),
    ("VONAU FLASH","Sanofi Medley",1,1),
    ("IVERMECTINA VMC","Cimed",1,1),
    ("ALIVIUM","Uniao Quimica",1,1),
    ("DIPIRONA GM2","SANOFI-AVENTIS",1,1),
    ("NEVRALGEX","Sanofi Medley",1,1),
    ("ENALAPRIL N.Q","Cimed",1,1)
]

def CREATE_Medicamentos(apps, schema_editor):
    medicamentos = apps.get_model('app1', 'Medicamentos')

    for medicamento_nome, medicamento_fabricante, medicamento_apresentacao, medicamento_via in Medicamentos_default:
        medicamentos.objects.create(
            medicamento_nome = medicamento_nome,
            medicamento_fabricante = medicamento_fabricante,
            medicamento_apresentacao = medicamento_apresentacao,
            medicamento_via = medicamento_via
        )

class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20221020_1714'),
    ]

    operations = [
        migrations.RunPython(CREATE_Medicamentos)
    ]
