# Generated by Django 4.1 on 2022-09-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_event_alter_pessoas_pessoa_comorbidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uso_consumo',
            name='consumo_apresentacao',
            field=models.IntegerField(choices=[('1', 'Comprimido'), ('2', 'Dragea'), ('3', 'Gota'), ('4', 'Injetavel'), ('5', 'Ampola'), ('6', 'Bisnaga'), ('7', 'Unidade')], default=None, verbose_name='Apresentacao'),
        ),
        migrations.AlterField(
            model_name='uso_consumo',
            name='consumo_via',
            field=models.IntegerField(choices=[('1', 'Oral'), ('2', 'Intra-Venoso'), ('3', 'Nasal'), ('4', 'Ocular')], default=None),
        ),
    ]
