# Generated by Django 4.1 on 2022-09-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_estoque_individual_estoque_pessoa_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque_individual',
            options={'verbose_name': 'Estoque Individual', 'verbose_name_plural': 'Estoque Individuais'},
        ),
        migrations.RemoveField(
            model_name='estoque_individual',
            name='estoque_pessoa_nome',
        ),
        migrations.RemoveField(
            model_name='estoque_individual',
            name='estoque_usos_consumo',
        ),
        migrations.AddField(
            model_name='estoque_individual',
            name='estoque_pessoa_nome',
            field=models.ManyToManyField(to='app1.pessoas', verbose_name='Residente'),
        ),
        migrations.AddField(
            model_name='estoque_individual',
            name='estoque_usos_consumo',
            field=models.ManyToManyField(to='app1.uso_consumo', verbose_name='Produto'),
        ),
    ]
