# Generated by Django 4.1 on 2022-09-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_estoque_individual_estoque_pessoa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_individual',
            name='estoque_usos_consumo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.uso_consumo', verbose_name='Produto'),
        ),
    ]
