# Generated by Django 4.1 on 2022-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_uso_consumo_consumo_apresentacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoas_Comorbidades',
        ),
        migrations.AddField(
            model_name='ocorrencias',
            name='ocorrencia_observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='estoque_individual',
            name='estoque_movimento',
            field=models.CharField(choices=[(1, 'Entrada'), (2, 'Saida')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='ocorrencias',
            name='ocorrencia_nome',
            field=models.CharField(choices=[(1, 'Agressividade'), (2, 'Alteracoes Glicemia'), (3, 'Cefaleia'), (4, 'Convulcao'), (5, 'Cuidado Paliativo'), (6, 'Deficit Motor'), (7, 'Desidratacao'), (8, 'Desnutricao'), (9, 'Diarreia'), (10, 'Doencas Respiratorias'), (11, 'Dor Abdominal'), (12, 'Dor Epigastrica'), (13, 'dor Torassica'), (14, 'Entorce'), (15, 'Escabiose'), (16, 'Febre'), (17, 'FR Alterada'), (18, 'Ematoma'), (19, 'Infeccao TRato Urinario'), (20, 'Internacao'), (21, 'Lesao de Pele'), (22, 'Liberacao de Cateteres e Sondas'), (23, 'Modificacao de Prescricao'), (24, 'Neutropenia Febril'), (25, 'Obito'), (26, 'PA Alterada'), (27, 'Queda'), (28, 'Retirada de Dispositivo')], default='', max_length=2, verbose_name='Ocorrencia'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_CPF',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_classe',
            field=models.IntegerField(choices=[(1, 'Cuidador'), (2, 'Residente'), (3, 'Responsavel')]),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_plano',
            field=models.IntegerField(blank=True, choices=[(1, 'PARTICULAR'), (2, 'SUS'), (3, 'CONVENIO')], null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pessoa_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='prescricao_dose',
            field=models.IntegerField(choices=[(1, '1/4'), (2, '1/2'), (3, '3/4'), (4, '1'), (5, '1 + 1/4'), (6, '1 + 1/2'), (7, '1 + 3/4')], default=''),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='prescricao_frequencia',
            field=models.IntegerField(choices=[(1, 'Horario'), (2, 'Diario'), (3, 'Semanal'), (4, 'Mensal'), (5, 'Dias Alternados'), (6, 'Criterio Medico')], default=''),
        ),
        migrations.AlterField(
            model_name='uso_consumo',
            name='consumo_apresentacao',
            field=models.IntegerField(choices=[(1, 'Comprimido'), (2, 'Dragea'), (3, 'Gota'), (4, 'Injetavel'), (5, 'Ampola'), (6, 'Bisnaga'), (7, 'Unidade'), (8, 'Adesivo'), (9, 'Aerosol'), (10, 'Bolsa'), (11, 'Capsula'), (12, 'Colirio'), (13, 'Creme'), (14, 'Envelope'), (15, 'Inalatorio'), (16, 'Injetavel UI'), (17, 'Pilula'), (18, 'Pomada'), (19, 'Sache'), (20, 'Seringa'), (21, 'Shampoo'), (22, 'Solucao Gotas'), (23, 'Solucao ML'), (24, 'Solucao UI'), (25, 'Suspencao'), (26, 'Xarope'), (27, 'Tablete')], default=None, verbose_name='Apresentacao'),
        ),
        migrations.AlterField(
            model_name='uso_consumo',
            name='consumo_via',
            field=models.IntegerField(choices=[(1, 'Oral'), (2, 'Intra-Venoso'), (3, 'Nasal'), (4, 'Ocular'), (5, 'Intramuscular'), (6, 'Topico'), (7, 'Nebulizacao'), (8, 'Otologica'), (9, 'Retal'), (10, 'Sonda-Nasoenteral'), (11, 'Gastrostomia'), (12, 'Sub-cutanea'), (13, 'Sub-lingual'), (14, 'Vaginal')], default=None),
        ),
    ]
