# Generated by Django 4.1 on 2022-10-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_sinalvital_options_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='medicamento_nome',
            field=models.CharField(default='', max_length=50, verbose_name='Medicamento'),
        ),
    ]
