# Generated by Django 4.1 on 2022-09-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_estoque_individual_estoque_usos_consumo'),
        ('app1', '0005_alter_estoque_individual_options_and_more'),
    ]

    operations = [
    ]
