# Generated by Django 4.1 on 2022-10-19 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_medicamentos_medicamento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinalvital',
            name='sinalVital_fc',
            field=models.IntegerField(default=0, verbose_name='Frequencia Cardiaca'),
        ),
        migrations.AlterField(
            model_name='sinalvital',
            name='sinalVital_fr',
            field=models.IntegerField(default=0, verbose_name='Frequencia Respiratoria'),
        ),
        migrations.AlterField(
            model_name='sinalvital',
            name='sinalVital_pad',
            field=models.IntegerField(default=0, verbose_name='P.A. Diastolica'),
        ),
        migrations.AlterField(
            model_name='sinalvital',
            name='sinalVital_pas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(240), django.core.validators.MinValueValidator(60)], verbose_name='P.A. Sistolica'),
        ),
        migrations.AlterField(
            model_name='sinalvital',
            name='sinalVital_temp',
            field=models.FloatField(default=0, verbose_name='Temperatura'),
        ),
    ]
